rule all:
    input:
        "/home/users/dkyriakis/PhD/Projects/Yahaya/1.QC/QC_list_data.rds",
        "/home/users/dkyriakis/PhD/Projects/Yahaya/2.Preprocess/Fl_QC_list_data.rds",
        "/home/users/dkyriakis/PhD/Projects/Yahaya/3.Projection/Liger_Merged.rds",
        "/home/users/dkyriakis/PhD/Projects/Yahaya/4.Clustering/Liger_Merged_CL.rds",
        "/home/users/dkyriakis/PhD/Projects/Yahaya/5.Seperation/Mouse.rds",
        "/home/users/dkyriakis/PhD/Projects/Yahaya/6.Mouse_Analysis/Mouse.rds"



# ==================================================================== ReadFiles ======================================================================
rule ReadFiles:
    input:
        "/work/projects/esprit/Dropseq_projects/LIH2/new/mouse/counts/"
    output:
        "/home/users/dkyriakis/PhD/Projects/Yahaya/1.QC/QC_list_data.rds"
    shell:
        "Rscript 1.ReadFiles.R"
# ------------------------------------------------------------------------------------------------------------------------------------------------------


# ==================================================================== Preprocess ======================================================================
rule Preprocess:
    input:
        "/home/users/dkyriakis/PhD/Projects/Yahaya/1.QC/QC_list_data.rds"
    output:
        "/home/users/dkyriakis/PhD/Projects/Yahaya/2.Preprocess/Fl_QC_list_data.rds"
    shell:
        "Rscript 2.preproces.R"
# ------------------------------------------------------------------------------------------------------------------------------------------------------


# ==================================================================== Projection ======================================================================
rule Projection:
    input:
        f1="/home/users/dkyriakis/PhD/Projects/Yahaya/2.Preprocess/Fl_QC_list_data.rds"
    output:
        "/home/users/dkyriakis/PhD/Projects/Yahaya/3.Projection/Liger_Merged.rds"
    shell:
        "Rscript 3.Projection.R"
# ------------------------------------------------------------------------------------------------------------------------------------------------------


# ==================================================================== Clustering ======================================================================
rule Clustering:
    input:
        "/home/users/dkyriakis/PhD/Projects/Yahaya/3.Projection/Liger_Merged.rds"
    output:
        "/home/users/dkyriakis/PhD/Projects/Yahaya/4.Clustering/Liger_Merged_CL.rds"
    shell:
        "Rscript 4.Clustering.R"
# ------------------------------------------------------------------------------------------------------------------------------------------------------



# ==================================================================== DF Analysis ======================================================================
rule Seperation:
    input:
        "/home/users/dkyriakis/PhD/Projects/Yahaya/4.Clustering/Liger_Merged_CL.rds"
    output:
        "/home/users/dkyriakis/PhD/Projects/Yahaya/5.Seperation/Mouse.rds"
    shell:
        "Rscript 0.hm_sep.R"
# ------------------------------------------------------------------------------------------------------------------------------------------------------



# ==================================================================== DF Analysis ======================================================================
rule Mouse_Analysis:
    input:
        "/home/users/dkyriakis/PhD/Projects/Yahaya/5.Seperation/Mouse.rds"
    output:
        "/home/users/dkyriakis/PhD/Projects/Yahaya/6.Mouse_Analysis/Mouse.rds"
    shell:
        "Rscript 6.Mouse_Analysis.R"
# ------------------------------------------------------------------------------------------------------------------------------------------------------

